-- cześć 1 - Operator CONTAINS - Podstawy

-- zad 1
CREATE TABLE CYTATY AS SELECT * FROM ZTPD.CYTATY;

-- zad 2
SELECT AUTOR, TEKST 
FROM CYTATY 
WHERE LOWER(TEKST) LIKE '%optymista%'
AND LOWER(TEKST) LIKE '%pesymista%';

-- zad 3 
CREATE INDEX CYTATY_IDX ON
CYTATY(TEKST)
INDEXTYPE IS CTXSYS.CONTEXT;

-- zad 4 
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'optymista AND pesymista', 1) > 0;

-- zad 5
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'pesymista AND NOT optymista', 1) > 0;

--zad 6
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'NEAR((optymista, pesymista), 3)') > 0;

-- zad 7 
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'NEAR((optymista, pesymista), 10)') > 0;

-- zad 8
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%') > 0;

-- zad 9 
SELECT AUTOR, TEKST, SCORE(1) DOPASOWANIE
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%', 1) > 0;

-- zad 10 
SELECT AUTOR, TEKST, SCORE(1) DOPASOWANIE
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%', 1) > 0
ORDER BY DOPASOWANIE DESC
FETCH FIRST 1 ROWS ONLY;

-- zad 11
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'FUZZY(probelm)', 1) > 0;

-- zad 12 
INSERT INTO CYTATY (ID, AUTOR, TEKST)
VALUES ((SELECT MAX(ID) + 1 FROM CYTATY), 'Bertrand Russell', 'To smutne, że głupcy są tacy pewni siebie, a ludzie rozsądni tacy pełni wątpliwości.');
COMMIT;

-- zad 13
SELECT AUTOR, TEKST 
FROM CYTATY
WHERE CONTAINS(TEKST, 'głupcy') > 0;

-- zad 14 
SELECT * FROM DR$CYTATY_IDX$I;

-- zad 15 
DROP INDEX CYTATY_IDX;

CREATE INDEX CYTATY_IDX ON
CYTATY(TEKST)
INDEXTYPE IS CTXSYS.CONTEXT;

-- zad 16 
SELECT * FROM DR$CYTATY_IDX$I;

SELECT AUTOR, TEKST 
FROM CYTATY
WHERE CONTAINS(TEKST, 'głupcy') > 0;

-- zad 17 
DROP INDEX CYTATY_IDX;
DROP TABLE CYTATY;

-- część druga - Zaawansowane indeksowanie i wyszukiwanie 

-- zad 1
CREATE TABLE QUOTES AS SELECT * FROM ZTPD.QUOTES; 

-- zad 2
CREATE INDEX QUOTES_IDX ON
QUOTES(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT;

-- zad 3
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'work') > 0;

SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, '$work') > 0;

SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'working') > 0;

SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, '$working') > 0;

-- zad 4
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'it') > 0;

-- zad 5 
SELECT * FROM CTX_STOPLISTS;

-- zad 6
SELECT * FROM CTX_STOPWORDS;

-- zad 7
DROP INDEX QUOTES_IDX;

CREATE INDEX QUOTES_IDX ON
QUOTES(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('stoplist CTXSYS.EMPTY_STOPLIST');

-- zad 8 
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'it') > 0;

-- zad 9
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'fool AND humans') > 0;

-- zad 10 
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'fool AND computer') > 0;

-- zad 11
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, '(fool AND computer) within SENTENCE') > 0;

-- zad 12 
DROP INDEX QUOTES_IDX;

-- zad 13
begin
    ctx_ddl.create_section_group('nullgroup', 'NULL_SECTION_GROUP');
    ctx_ddl.add_special_section('nullgroup', 'SENTENCE');
    ctx_ddl.add_special_section('nullgroup', 'PARAGRAPH');
end;

-- zad 14
CREATE INDEX QUOTES_IDX ON
QUOTES(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('section group nullgroup');

-- zad 15
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, '(fool AND humans) WITHIN SENTENCE') > 0;

SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, '(fool AND computer) WITHIN SENTENCE') > 0;

-- zad 16 
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'humans') > 0;

-- zad 17 
DROP INDEX QUOTES_IDX;

begin
    ctx_ddl.create_preference('lex_z_m','BASIC_LEXER');
    ctx_ddl.set_attribute('lex_z_m',
    'printjoins', '_-');
    ctx_ddl.set_attribute ('lex_z_m',
    'index_text', 'YES');
end;

CREATE INDEX QUOTES_IDX ON
QUOTES(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS('LEXER lex_z_m');

-- zad 18
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'humans') > 0;

-- zad 19 
SELECT * FROM QUOTES
WHERE CONTAINS(TEXT, 'non\-humans') > 0;

-- zad 20
DROP INDEX QUOTES_IDX;

DROP TABLE QUOTES;

begin
    ctx_ddl.drop_preference('lex_z_m');
end;
